global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'metrics-server'
    static_configs:
      - targets: ['metrics-server:3000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'ml-predictor'
    static_configs:
      - targets: ['ml-predictor:5000']
